I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/debug/tile_editor_logic.rpy", line 4, in script
    python:
  File "game/debug/tile_editor_logic.rpy", line 5, in <module>
    game = Game()
  File "game/script/3__Game_class.rpy", line 37, in __init__
    settings["tilemap"][y][x]
KeyError: u'tilemap'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/debug/tile_editor_logic.rpy", line 4, in script
    python:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/debug/tile_editor_logic.rpy", line 5, in <module>
    game = Game()
  File "game/script/3__Game_class.rpy", line 37, in __init__
    settings["tilemap"][y][x]
KeyError: u'tilemap'

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
ParisIsBurning 1.0
Sat Feb 26 10:49:21 2022
