I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 16, in script call
    call lab_render from _call_lab_render
  File "game/game_render.rpy", line 16, in script call
    call screen sce_gameloop
  File "game/script.rpy", line 16, in script call
    call lab_render from _call_lab_render
  File "game/game_render.rpy", line 16, in script call
    call screen sce_gameloop
  File "game/01_fyn_event-tiles.rpy", line 21, in script call
    python:
  File "game/script.rpy", line 16, in script call
    call lab_render from _call_lab_render
  File "game/game_render.rpy", line 16, in script call
    call screen sce_gameloop
  File "game/01_fyn_event-tiles.rpy", line 21, in script call
    python:
  File "game/script.rpy", line 16, in script call
    call lab_render from _call_lab_render
  File "game/game_render.rpy", line 16, in script call
    call screen sce_gameloop
  File "game/script.rpy", line 16, in script call
    call lab_render from _call_lab_render
  File "game/game_render.rpy", line 16, in script call
    call screen sce_gameloop
  File "game/01_fyn_event-tiles.rpy", line 21, in script call
    python:
  File "game/script.rpy", line 16, in script call
    call lab_render from _call_lab_render
  File "game/game_render.rpy", line 16, in script call
    call screen sce_gameloop
  File "game/01_fyn_event-tiles.rpy", line 21, in script call
    python:
ScriptError: could not find label 'label_D2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 662, in main
    run(restart)
  File "renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "renpy/execution.py", line 922, in run_context
    context.run()
  File "game/script.rpy", line 16, in script call
    call lab_render from _call_lab_render
  File "game/game_render.rpy", line 16, in script call
    call screen sce_gameloop
  File "game/script.rpy", line 16, in script call
    call lab_render from _call_lab_render
  File "game/game_render.rpy", line 16, in script call
    call screen sce_gameloop
  File "game/01_fyn_event-tiles.rpy", line 21, in script call
    python:
  File "game/script.rpy", line 16, in script call
    call lab_render from _call_lab_render
  File "game/game_render.rpy", line 16, in script call
    call screen sce_gameloop
  File "game/01_fyn_event-tiles.rpy", line 21, in script call
    python:
  File "game/script.rpy", line 16, in script call
    call lab_render from _call_lab_render
  File "game/game_render.rpy", line 16, in script call
    call screen sce_gameloop
  File "game/script.rpy", line 16, in script call
    call lab_render from _call_lab_render
  File "game/game_render.rpy", line 16, in script call
    call screen sce_gameloop
  File "game/01_fyn_event-tiles.rpy", line 21, in script call
    python:
  File "game/script.rpy", line 16, in script call
    call lab_render from _call_lab_render
  File "game/game_render.rpy", line 16, in script call
    call screen sce_gameloop
  File "game/01_fyn_event-tiles.rpy", line 21, in script call
    python:
  File "renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'label_D2'.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
RENPY 1.0
Mon Jan 31 11:27:41 2022
